# Generated by Django 2.2.1 on 2019-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
