# Generated by Django 2.2.1 on 2019-06-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_auto_20190526_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmation',
            old_name='code',
            new_name='code_2fa',
        ),
    ]
