# Generated by Django 2.2.1 on 2019-06-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_auto_20190605_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
