# Generated by Django 2.2.1 on 2019-05-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('address_addon', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.IntegerField(choices=[(1, 'OWN'), (2, 'FOREIGN')], default=1)),
                ('balance', models.BigIntegerField(default=0)),
                ('n', models.IntegerField()),
                ('private_key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='keys.PrivateKey')),
            ],
        ),
    ]
