# Generated by Django 2.2.1 on 2019-05-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0)),
                ('validation', models.CharField(blank=True, max_length=1024)),
                ('period', models.IntegerField(blank=True, default=0, null=True)),
                ('private_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.PrivateKey')),
            ],
        ),
        migrations.CreateModel(
            name='FirewallAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('firewall_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firewall.FirewallRule')),
            ],
        ),
    ]
