# Generated by Django 2.2.1 on 2019-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallrule',
            name='validation',
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='signatures_required',
            field=models.IntegerField(default=1),
        ),
    ]
