# Generated by Django 2.2.1 on 2019-05-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firewall', '0002_auto_20190526_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRuleSignatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewall_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firewall.FirewallRule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
